# Generated by Django 5.2.3 on 2025-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_online', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publicprofile',
            new_name='profile_onl_is_publ_e3fc7b_idx',
            old_name='profile_online_is_publ_7614b5_idx',
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profileschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')]),
        ),
    ]
