# Generated by Django 5.2.3 on 2025-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_online', '0002_rename_profile_online_is_publ_7614b5_idx_profile_onl_is_publ_e3fc7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
