# Generated by Django 5.2.3 on 2025-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_online', '0004_appointmentonline_scheduleexception_scheduleonline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleonline',
            unique_together=set(),
        ),
    ]
