# Generated by Django 5.2.3 on 2026-02-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_date_sale_creationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
