# Generated by Django 5.2.3 on 2026-02-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='taxes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
