# Generated by Django 5.2.3 on 2026-02-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepaymentmethod',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='sales.salehistory'),
        ),
    ]
