# Generated by Django 5.2.3 on 2026-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salepaymentmethod_sale_salepaymentmethod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name_sale',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='note_cancelled',
            field=models.TextField(blank=True, null=True),
        ),
    ]
