# Generated by Django 5.2.3 on 2025-09-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Source',
                'verbose_name_plural': 'Customer Sources',
                'db_table': 'customer.customer_source',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code, e.g., #3498db', max_length=7)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
                'db_table': 'customer.customer_type',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('this_customer_is_a_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_cellphone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('id_company', models.BigIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customersource')),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customertype')),
            ],
            options={
                'db_table': 'customer.customer',
                'indexes': [models.Index(fields=['name'], name='idx_customer_name'), models.Index(fields=['email'], name='idx_customer_email'), models.Index(fields=['cellphone'], name='idx_customer_cellphone'), models.Index(fields=['id_company'], name='idx_customer_id_company'), models.Index(fields=['activated'], name='idx_customer_activated'), models.Index(fields=['company_name'], name='idx_customer_company_name'), models.Index(fields=['email', 'id_company'], name='idx_customer_email_branch')],
            },
        ),
    ]
