# Generated by Django 5.2.3 on 2025-09-14 15:32

import apps.customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sources', to='core.company')),
            ],
            options={
                'verbose_name': 'Customer Source',
                'verbose_name_plural': 'Customer Sources',
                'db_table': 'customers_customer_source',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code, e.g., #3498db', max_length=7)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_types', to='core.company')),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
                'db_table': 'customers_customer_type',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.customers.models.customer_avatar_path)),
                ('_name', models.BinaryField(blank=True, db_column='name', null=True)),
                ('_email', models.BinaryField(blank=True, db_column='email', null=True)),
                ('_phone', models.BinaryField(blank=True, db_column='phone', null=True)),
                ('_cellphone', models.BinaryField(blank=True, db_column='cellphone', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('_address', models.BinaryField(blank=True, db_column='address', null=True)),
                ('_city', models.BinaryField(blank=True, db_column='city', null=True)),
                ('_state', models.BinaryField(blank=True, db_column='state', null=True)),
                ('_postal_code', models.BinaryField(blank=True, db_column='postal_code', null=True)),
                ('_num_ext', models.BinaryField(blank=True, db_column='num_ext', null=True)),
                ('_num_int', models.BinaryField(blank=True, db_column='num_int', null=True)),
                ('_reference', models.BinaryField(blank=True, db_column='reference', null=True)),
                ('this_customer_is_a_company', models.BooleanField(default=False)),
                ('_company_name', models.BinaryField(blank=True, db_column='company_name', null=True)),
                ('_contact_name', models.BinaryField(blank=True, db_column='contact_name', null=True)),
                ('_contact_email', models.BinaryField(blank=True, db_column='contact_email', null=True)),
                ('_contact_cellphone', models.BinaryField(blank=True, db_column='contact_cellphone', null=True)),
                ('_contact_phone', models.BinaryField(blank=True, db_column='contact_phone', null=True)),
                ('_website', models.BinaryField(blank=True, db_column='website', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('number_of_price_of_sale', models.SmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer', to='core.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer', to='core.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customersource')),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customertype')),
            ],
            options={
                'db_table': 'customers_customer',
                'indexes': [models.Index(fields=['company'], name='idx_customer_company'), models.Index(fields=['activated'], name='idx_customer_activated')],
            },
        ),
    ]
