# Generated by Django 5.2.3 on 2025-09-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_language'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='idx_customer_id_company',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='idx_customer_email_branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_company',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer', to='core.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_ext',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_int',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_price_of_sale',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sources', to='core.company'),
        ),
        migrations.AddField(
            model_name='customertype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_types', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='customersource',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customertype',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company'], name='idx_customer_company'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'company'], name='idx_customer_email_branch'),
        ),
    ]
