# Generated by Django 5.2.3 on 2025-09-12 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_branch_customuser_branch_and_more'),
        ('customers', '0002_remove_customer_idx_customer_id_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer', to='core.branch'),
        ),
    ]
