# Generated by Django 5.2.3 on 2025-09-14 21:36

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_branch_alter_customer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_cellphone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_contact_cellphone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_contact_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_contact_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_contact_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_num_ext',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_num_int',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_reference',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='_website',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='celular',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='cellphone', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='city', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='company_name', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_cellphone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='contact_cellphone', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='contact_email', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='contact_name', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='contact_phone', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='email', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='name', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_ext',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='num_int', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='postal_code', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='reference', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='website', null=True),
        ),
    ]
