# Generated by Django 5.2.3 on 2025-09-17 14:01

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer__address_remove_customer__cellphone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='celular',
            new_name='cellphone',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('F', 'Woman'), ('O', 'Other')], db_column='gender', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_int',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='num_int', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='phone', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_ext',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='num_ext', null=True),
        ),
    ]
