# Generated by Django 5.2.3 on 2025-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_celular_customer_cellphone_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sku',
            field=models.CharField(blank=True, db_column='sku', max_length=300, null=True),
        ),
    ]
