# Generated by Django 5.2.3 on 2025-10-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_sku'),
    ]

    operations = [
    ]
