# Generated by Django 5.2.3 on 2026-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20251010_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
