# Generated by Django 5.2.3 on 2025-09-19 03:24

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_branch_company'),
        ('customers', '0005_rename_celular_customer_cellphone_customer_gender_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('date_performed', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.consultation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='customers.customer')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.professionaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('finalized', 'Finalizada'), ('canceled', 'Cancelada')], default='draft', max_length=10)),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.company')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='services.consultation')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.professionaldata')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_item', to='medical_history.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skull', models.CharField(max_length=100)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chronic_conditions', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('allergies', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('medications', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('surgeries', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('immunizations', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('family_history', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('lifestyle', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('emergency_contact_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('emergency_contact_phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('emergency_contact_relation', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info_other_doctor', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_informations', to='core.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_informations', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_information', to='customers.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'skull'), name='unique_skull_per_company')],
            },
        ),
    ]
