# Generated by Django 5.2.3 on 2025-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, default='America/Mexico_City', max_length=50),
        ),
    ]
