# Generated by Django 5.2.3 on 2025-09-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='id_company',
            new_name='company',
        ),
    ]
