# Generated by Django 5.2.3 on 2025-09-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_company_branch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(db_column='company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
    ]
