# Generated by Django 5.2.3 on 2025-08-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
