# Generated by Django 5.2.3 on 2025-09-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
                ('app', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserType',
            new_name='UserDepartment',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_department',
            field=models.ForeignKey(db_column='id_user_department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userdepartment'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
                ('id_company', models.ForeignKey(db_column='id_company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
            ],
            options={
                'db_table': 'companies_roles',
                'unique_together': {('id_company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permit')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userrole')),
            ],
            options={
                'unique_together': {('role', 'permit')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(db_column='id_user_role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userrole'),
        ),
        migrations.DeleteModel(
            name='Permits',
        ),
    ]
