# Generated by Django 5.2.3 on 2025-10-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permit_rename_usertype_userdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
