# Generated by Django 5.2.3 on 2025-09-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='id_company',
            new_name='company',
        ),
    ]
