# Generated by Django 5.2.3 on 2025-10-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdepartment_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
