# Generated by Django 5.2.3 on 2025-10-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userdepartment_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_cellphone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='_phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='MX', max_length=2, null=True),
        ),
    ]
