# Generated by Django 5.2.3 on 2025-10-09 23:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser__cellphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='email', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='name', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='phone', null=True),
        ),
    ]
