# Generated by Django 5.2.3 on 2025-10-09 23:34

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_email_customuser_name_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cellphone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_column='cellphone', null=True),
        ),
    ]
