# Generated by Django 5.2.3 on 2025-10-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_hash',
        ),
    ]
