# Generated by Django 5.2.3 on 2025-10-09 23:45

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customuser_email_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='_date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='date_of_birth', null=True),
        ),
    ]
