# Generated by Django 5.2.3 on 2025-10-30 03:51

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='_bank_account',
        ),
        migrations.RemoveField(
            model_name='company',
            name='_bank_account',
        ),
        migrations.RemoveField(
            model_name='company',
            name='_google_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='_tax_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='decimal_separator',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AddField(
            model_name='branch',
            name='thousands_separator',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, db_column='bank_account', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='google_password',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, db_column='google_password', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, db_column='tax_id', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='password_google',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='user_google',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_user',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BranchBillingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, help_text='RFC (MX), NIT (CO), NIF (ES), EIN (US), NIP (PL), etc.', max_length=50, null=True)),
                ('secondary_id', models.CharField(blank=True, help_text='CURP (MX), DNI (ES), PESEL (PL) or other document.', max_length=50, null=True)),
                ('legal_name', models.CharField(help_text='Name that have the company in the country', max_length=255)),
                ('fiscal_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(help_text='example. MX, US, CO, ES, PL', max_length=2)),
                ('digital_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('private_key', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('private_key_password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fiscal_engine', models.CharField(default='generic', help_text="Tax engine or system: 'sat_mx', 'irs_us', 'aeat_es', 'zapl_pl', 'facturama', etc.", max_length=50)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='core.branch')),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Billing Data',
                'verbose_name_plural': 'Billing Data',
                'db_table': 'companies_branch_billing_data',
            },
        ),
        migrations.CreateModel(
            name='BranchSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.branch')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('branch', 'day_of_week')},
            },
        ),
    ]
