# Generated by Django 5.2.3 on 2025-10-30 03:57

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_branch__bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_days',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='google_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='google_user',
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_account',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, db_column='bank_account', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
