# Generated by Django 5.2.3 on 2025-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_branch_closing_time_remove_branch_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='decimal_separator',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='thousands_separator',
            field=models.CharField(default=',', max_length=1),
        ),
    ]
