# Generated by Django 5.2.3 on 2025-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_date_format_customuser_decimal_separator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchbillingdata',
            old_name='fiscal_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='branchbillingdata',
            name='cologne',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='branchbillingdata',
            name='municipality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='branchbillingdata',
            name='num_ins',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='branchbillingdata',
            name='num_out',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
