# Generated by Django 5.2.3 on 2025-12-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_fiscal_address_branchbillingdata_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('waba_id', models.CharField(max_length=50)),
                ('phone_number_id', models.CharField(max_length=50)),
                ('display_phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('error', 'Error')], default='connected', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(db_column='company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
            ],
        ),
    ]
