# Generated by Django 5.2.3 on 2025-12-12 01:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_whatsappaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='phone_number_id',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='waba_id',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
