# Generated by Django 5.2.3 on 2025-12-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_whatsappaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
