# Generated by Django 5.2.3 on 2025-12-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_branch_public_slug_customuser_public_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
