# Generated by Django 5.2.3 on 2025-12-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_branch_is_public_customuser_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='public_slug',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_slug',
        ),
    ]
