# Generated by Django 5.2.3 on 2025-12-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_branch_is_public_remove_branch_public_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='messages_sent_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='monthly_limit',
            field=models.IntegerField(default=50),
        ),
    ]
