# Generated by Django 5.2.3 on 2025-12-24 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_whatsappaccount_messages_sent_this_month_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Pro')], unique=True)),
                ('name', models.CharField(max_length=50)),
                ('max_messages', models.PositiveIntegerField(default=0)),
                ('storage_gb', models.FloatField(default=0)),
                ('max_drives', models.PositiveIntegerField(default=1)),
                ('max_clients', models.PositiveIntegerField(default=60)),
                ('max_appoints', models.PositiveIntegerField(default=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='free', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='manual', max_length=30)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('used_messages', models.PositiveIntegerField(default=0)),
                ('used_storage_gb', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
