# Generated by Django 5.2.3 on 2026-01-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_subscriptionplan_usersession_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
