# Generated by Django 5.2.3 on 2026-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='template',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
