# Generated by Django 5.2.3 on 2026-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usersubscription_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='template',
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='template',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
