# Generated by Django 5.2.3 on 2026-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_usersubscription_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='template',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
