# Generated by Django 5.2.3 on 2026-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_whatsappaccount_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='template_24h',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
