# Generated by Django 5.2.3 on 2026-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_whatsappaccount_template_24h'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappaccount',
            old_name='template',
            new_name='template_birthday',
        ),
        migrations.RenameField(
            model_name='whatsappaccount',
            old_name='template_24h',
            new_name='template_day_before',
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='template_qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='template_today',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
