# Generated by Django 5.2.3 on 2026-03-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_template_whatsappaccount_template_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='template_four_before',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
