# Generated by Django 5.2.3 on 2026-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_whatsappaccount_template_four_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_branches',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
