# Generated by Django 5.2.3 on 2026-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_customuser_superuser_subscriptionplan_max_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
