# Generated by Django 5.2.3 on 2026-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_customuser_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
