# Generated by Django 5.2.3 on 2026-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customuser_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
