# Generated by Django 5.2.3 on 2026-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_subscriptionplan_max_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Pro')]),
        ),
    ]
