# Generated by Django 5.2.3 on 2026-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='template',
            field=models.TextField(null=True),
        ),
    ]
