# Generated by Django 5.2.3 on 2026-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_whatsappaccount_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_account',
            field=models.BooleanField(default=False),
        ),
    ]
