# Generated by Django 5.2.3 on 2026-02-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0025_customuser_terms_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('activated', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_company_category_product', to='core.company')),
            ],
            options={
                'db_table': 'services_product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('activated', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_company_departament_product', to='core.company')),
            ],
            options={
                'db_table': 'services_product_department',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('skus', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_with_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activated', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('pack_type', models.IntegerField(choices=[(0, 'product'), (1, 'service'), (2, 'pack/combo')], default=1, help_text='Tipo de pack')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_company_pack', to='core.company')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.productcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='services.productdepartment')),
            ],
            options={
                'db_table': 'services_packs',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto, ej: 16 para 16%', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_branch_tax', to='core.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_company_tax', to='core.company')),
            ],
            options={
                'db_table': 'services.tax',
            },
        ),
        migrations.CreateModel(
            name='PackTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='services.pack')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='services.tax')),
            ],
            options={
                'db_table': 'services_pack_tax',
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['company'], name='idx_category_company'),
        ),
        migrations.AddIndex(
            model_name='productdepartment',
            index=models.Index(fields=['name'], name='idx_department_name'),
        ),
        migrations.AddIndex(
            model_name='productdepartment',
            index=models.Index(fields=['company'], name='idx_department_company'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['name'], name='idx_pack_name'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['skus'], name='idx_pack_sku'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['company'], name='idx_pack_id_company'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['activated'], name='idx_pack_activated'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['name'], name='idx_tax_name'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['branch'], name='idx_tax_branch'),
        ),
        migrations.AlterUniqueTogether(
            name='packtax',
            unique_together={('pack', 'tax')},
        ),
    ]
