# Generated by Django 5.2.3 on 2026-02-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tax',
            table='services_tax',
        ),
    ]
