# Generated by Django 5.2.3 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='skus',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
