# Generated by Django 5.2.3 on 2026-02-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_terms_accepted_and_more'),
        ('services', '0002_alter_tax_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_with_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activated', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services_branch_pack',
            },
        ),
        migrations.RemoveIndex(
            model_name='tax',
            name='idx_tax_branch',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='price_with_taxes',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='branch',
        ),
        migrations.AlterField(
            model_name='tax',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_company_tax', to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchpack',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AddField(
            model_name='branchpack',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='branchpack',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='services.pack'),
        ),
        migrations.AddIndex(
            model_name='branchpack',
            index=models.Index(fields=['company', 'branch'], name='services_br_company_3aab8c_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpack',
            index=models.Index(fields=['company', 'pack'], name='services_br_company_1abf8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchpack',
            unique_together={('branch', 'pack')},
        ),
    ]
