# Generated by Django 5.2.3 on 2025-11-02 05:01

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_rename_fiscal_address_branchbillingdata_street_and_more'),
        ('customers', '0007_auto_20251010_1351'),
        ('files', '0004_folderpermission_can_see_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOdontogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False, help_text='Indicates if the odontogram is locked and cannot be modified.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram', to='customers.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('xray', 'Radiografía'), ('photo', 'Fotografía'), ('document', 'Documento'), ('payment', 'Historial de pago'), ('lab_report', 'Informe de laboratorio'), ('other', 'Otro')], default='other', max_length=20)),
                ('visible_to_patient', models.BooleanField(default=False)),
                ('description_fot_the_patient', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram_links', to='files.file')),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram_files', to='odontograma.odontogram')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogram_uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontogram File',
                'verbose_name_plural': 'Odontogram Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FDI_number', models.PositiveSmallIntegerField(unique=True)),
                ('name_key', models.CharField(blank=True, choices=[(11, 'odontogram.tooth.upper_right.central_incisor'), (12, 'odontogram.tooth.upper_right.lateral_incisor'), (13, 'odontogram.tooth.upper_right.canine'), (14, 'odontogram.tooth.upper_right.first_premolar'), (15, 'odontogram.tooth.upper_right.second_premolar'), (16, 'odontogram.tooth.upper_right.first_molar'), (17, 'odontogram.tooth.upper_right.second_molar'), (18, 'odontogram.tooth.upper_right.third_molar'), (21, 'odontogram.tooth.upper_left.central_incisor'), (22, 'odontogram.tooth.upper_left.lateral_incisor'), (23, 'odontogram.tooth.upper_left.canine'), (24, 'odontogram.tooth.upper_left.first_premolar'), (25, 'odontogram.tooth.upper_left.second_premolar'), (26, 'odontogram.tooth.upper_left.first_molar'), (27, 'odontogram.tooth.upper_left.second_molar'), (28, 'odontogram.tooth.upper_left.third_molar'), (31, 'odontogram.tooth.lower_left.central_incisor'), (32, 'odontogram.tooth.lower_left.lateral_incisor'), (33, 'odontogram.tooth.lower_left.canine'), (34, 'odontogram.tooth.lower_left.first_premolar'), (35, 'odontogram.tooth.lower_left.second_premolar'), (36, 'odontogram.tooth.lower_left.first_molar'), (37, 'odontogram.tooth.lower_left.second_molar'), (38, 'odontogram.tooth.lower_left.third_molar'), (41, 'odontogram.tooth.lower_right.central_incisor'), (42, 'odontogram.tooth.lower_right.lateral_incisor'), (43, 'odontogram.tooth.lower_right.canine'), (44, 'odontogram.tooth.lower_right.first_premolar'), (45, 'odontogram.tooth.lower_right.second_premolar'), (46, 'odontogram.tooth.lower_right.first_molar'), (47, 'odontogram.tooth.lower_right.second_molar'), (48, 'odontogram.tooth.lower_right.third_molar'), (51, 'odontogram.tooth.upper_right.primary_central_incisor'), (52, 'odontogram.tooth.upper_right.primary_lateral_incisor'), (53, 'odontogram.tooth.upper_right.primary_canine'), (54, 'odontogram.tooth.upper_right.primary_first_molar'), (55, 'odontogram.tooth.upper_right.primary_second_molar'), (61, 'odontogram.tooth.upper_left.primary_central_incisor'), (62, 'odontogram.tooth.upper_left.primary_lateral_incisor'), (63, 'odontogram.tooth.upper_left.primary_canine'), (64, 'odontogram.tooth.upper_left.primary_first_molar'), (65, 'odontogram.tooth.upper_left.primary_second_molar'), (71, 'odontogram.tooth.lower_left.primary_central_incisor'), (72, 'odontogram.tooth.lower_left.primary_lateral_incisor'), (73, 'odontogram.tooth.lower_left.primary_canine'), (74, 'odontogram.tooth.lower_left.primary_first_molar'), (75, 'odontogram.tooth.lower_left.primary_second_molar'), (81, 'odontogram.tooth.lower_right.primary_central_incisor'), (82, 'odontogram.tooth.lower_right.primary_lateral_incisor'), (83, 'odontogram.tooth.lower_right.primary_canine'), (84, 'odontogram.tooth.lower_right.primary_first_molar'), (85, 'odontogram.tooth.lower_right.primary_second_molar')], max_length=200)),
                ('status', models.CharField(choices=[('healthy', 'Sano'), ('caries', 'Caries'), ('missing', 'Ausente'), ('filled', 'Empaste'), ('extracted', 'Extraído'), ('implanted', 'Implante'), ('crown', 'Corona'), ('fractured', 'Fracturado'), ('endodontic', 'Endodoncia'), ('other', 'Otro')], default='healthy', max_length=20)),
                ('diagnosis', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('surface_occlusal', models.CharField(blank=True, max_length=50, null=True)),
                ('surface_mesial', models.CharField(blank=True, max_length=50, null=True)),
                ('surface_distal', models.CharField(blank=True, max_length=50, null=True)),
                ('surface_lingual', models.CharField(blank=True, max_length=50, null=True)),
                ('surface_buccal', models.CharField(blank=True, max_length=50, null=True)),
                ('caries_depth', models.PositiveSmallIntegerField(choices=[(0, 'No cavities'), (1, 'Affected enamel'), (2, 'affected dentin'), (3, 'Close to the pulp'), (4, 'It compromises the pulp')], default=0, help_text='Indicates the level of depth of the caries on a scale of 0 to 4.')),
                ('svg_state', models.TextField(blank=True, help_text='SVG code that represents the current visual state of the tooth.', null=True)),
                ('treatments', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historyodontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='odontograma.historyodontogram')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teeth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['FDI_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='odontogram',
            constraint=models.UniqueConstraint(fields=('company', 'customer'), name='unique_odontogram_per_customer_per_company'),
        ),
        migrations.AddConstraint(
            model_name='odontogramfile',
            constraint=models.UniqueConstraint(fields=('odontogram', 'file'), name='unique_file_per_odontogram'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('historyodontogram', 'FDI_number')},
        ),
    ]
