# Generated by Django 5.2.3 on 2025-11-03 02:42

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontogram',
            name='svg',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
    ]
