# Generated by Django 5.2.3 on 2025-11-10 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_odontogram_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooth',
            name='surface_buccal',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='surface_distal',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='surface_lingual',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='surface_mesial',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='surface_occlusal',
        ),
        migrations.AddField(
            model_name='tooth',
            name='has_tartar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tooth',
            name='last_checkup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tooth',
            name='mobility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='tooth',
            name='status_gum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='tooth',
            name='surfaces',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
