# Generated by Django 5.2.3 on 2025-11-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0003_remove_tooth_surface_buccal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='svg_state',
            field=models.JSONField(blank=True, default=dict, help_text='SVG code that represents the current visual state of the tooth.'),
        ),
    ]
