# Generated by Django 5.2.3 on 2025-11-16 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_fiscal_address_branchbillingdata_street_and_more'),
        ('odontograma', '0004_alter_tooth_svg_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdontogramSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSystem', models.PositiveSmallIntegerField(choices=[(1, 'FDI'), (2, 'Universal')], default=1)),
                ('color_caries', models.CharField(default='#FF0000', max_length=7)),
                ('default_treatments', models.JSONField(default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram_settings', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram_settings', to='core.company')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'doctor'), name='unique_odontogram_per_doctor_per_company')],
            },
        ),
    ]
