# Generated by Django 5.2.3 on 2025-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0005_odontogramsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyodontogram',
            name='periodontograma',
            field=models.JSONField(default=dict),
        ),
    ]
