# Generated by Django 5.2.3 on 2025-11-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0006_historyodontogram_periodontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyodontogram',
            name='is_kid',
            field=models.BooleanField(default=False),
        ),
    ]
