# Generated by Django 5.2.3 on 2025-12-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0008_historyodontogram_is_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyodontogram',
            name='is_father',
            field=models.BooleanField(default=True),
        ),
    ]
