# Generated by Django 5.2.3 on 2025-12-08 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0009_alter_historyodontogram_is_father'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tooth',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='FDI_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='tooth',
            constraint=models.UniqueConstraint(fields=('historyodontogram', 'FDI_number'), name='unique_tooth_per_history'),
        ),
    ]
