# Generated by Django 5.2.3 on 2025-09-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAppoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#075EAD', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda_type_appoint',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert', models.TextField()),
                ('time_alert', models.IntegerField(default=0)),
                ('send_notification', models.BooleanField(default=True)),
                ('default_type_appoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.typeappoint')),
            ],
            options={
                'db_table': 'agenda_settings',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('time_alert', models.IntegerField(default=0)),
                ('priority', models.SmallIntegerField(default=0)),
                ('activate_event_all_the_day', models.BooleanField(default=False)),
                ('emails_guests', models.JSONField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('repeat_this_event', models.BooleanField(default=False)),
                ('time_repeat', models.SmallIntegerField(default=0)),
                ('finish_repeat_date', models.DateTimeField(blank=True, help_text='This is for that the ERP knows when to stop repeating this event', null=True)),
                ('send_notification', models.BooleanField(default=True)),
                ('i_am_free', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_type_appoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.typeappoint')),
            ],
            options={
                'db_table': 'agenda_appointments',
            },
        ),
    ]
