# Generated by Django 5.2.3 on 2025-08-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert', models.TextField()),
                ('time_alert', models.IntegerField(default=0)),
                ('send_notification', models.BooleanField(default=True)),
                ('default_type_appoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.typeappoint')),
            ],
            options={
                'db_table': 'agenda.prueba',
            },
        ),
    ]
