# Generated by Django 5.2.3 on 2025-09-19 03:56

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('token_uri', encrypted_model_fields.fields.EncryptedTextField()),
                ('client_id', encrypted_model_fields.fields.EncryptedTextField()),
                ('client_secret', encrypted_model_fields.fields.EncryptedTextField()),
                ('scopes', encrypted_model_fields.fields.EncryptedTextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
