# Generated by Django 5.2.3 on 2025-08-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_tableprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablePrueba',
        ),
    ]
