# Generated by Django 5.2.3 on 2025-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_googletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id_event_in_google_calendar',
            field=models.IntegerField(null=True),
        ),
    ]
