# Generated by Django 5.2.3 on 2025-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_delete_tableprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
