# Generated by Django 5.2.3 on 2025-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_appointment_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeappoint',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
