# Generated by Django 5.2.3 on 2025-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_appointment_id_event_in_google_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id_event_in_google_calendar',
            field=models.TextField(null=True, unique=True),
        ),
    ]
