# Generated by Django 5.2.3 on 2025-12-12 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_appointment_id_event_in_google_calendar'),
        ('customers', '0007_auto_20251010_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(db_column='customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
