# Generated by Django 5.2.3 on 2025-12-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
