# Generated by Django 5.2.3 on 2025-12-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('agenda', '0007_appointment_reminder_sent'),
    ]

    operations = [
    ]
