# Generated by Django 5.2.3 on 2025-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_merge_0002_initial_0007_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='online_appointment_id',
            field=models.IntegerField(blank=True, help_text='ID de la cita online relacionada', null=True),
        ),
    ]
