# Generated by Django 5.2.3 on 2025-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_appointment_online_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('P', 'agenda.status.pending'), ('C', 'agenda.status.confirmed'), ('X', 'agenda.status.cancelled')], db_index=True, default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_event_in_google_calendar',
            field=models.TextField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='online_appointment_id',
            field=models.IntegerField(blank=True, help_text='Online appointment ID', null=True),
        ),
    ]
