# Generated by Django 5.2.3 on 2026-01-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('P', 'agenda.status.pending'), ('C', 'agenda.status.confirmed'), ('X', 'agenda.status.cancelled'), ('A', 'agenda.status.attended'), ('N', 'agenda.status.no_show')], db_index=True, default='P', max_length=1),
        ),
    ]
