# Generated by Django 5.2.3 on 2025-10-16 14:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_alter_customuser_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3A7BD5', help_text='Color hexadecimal for the folder', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(db_column='branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('company', models.ForeignKey(db_column='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('creator_user', models.ForeignKey(db_column='employee', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'unique_together': {('branch', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('anchored', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(db_column='branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('company', models.ForeignKey(db_column='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('upload_user', models.ForeignKey(db_column='employee', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.folder')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('folder', 'key'), name='unique_key_per_folder')],
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_copy', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_upload_file', models.BooleanField(default=False)),
                ('can_update_file', models.BooleanField(default=False)),
                ('can_copy_file', models.BooleanField(default=False)),
                ('can_delete_file', models.BooleanField(default=False)),
                ('can_change_the_permission', models.BooleanField(default=False)),
                ('can_add_members', models.BooleanField(default=False)),
                ('can_delete_members', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.folder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
