# Generated by Django 5.2.3 on 2025-10-24 18:45

import apps.files.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderpermission',
            options={'verbose_name': 'Folder Permission', 'verbose_name_plural': 'Folder Permissions'},
        ),
        migrations.RenameField(
            model_name='folderpermission',
            old_name='can_delete',
            new_name='can_add_subfolder',
        ),
        migrations.RenameField(
            model_name='folderpermission',
            old_name='can_write',
            new_name='can_delete_folder',
        ),
        migrations.RenameField(
            model_name='folderpermission',
            old_name='can_copy',
            new_name='can_see_file',
        ),
        migrations.RenameField(
            model_name='folderpermission',
            old_name='can_read',
            new_name='can_see_the_files',
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_download_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_download_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_edit_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.files.models.file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.files.models.thumbnail_upload_path),
        ),
    ]
