# Generated by Django 5.2.3 on 2025-10-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_folderpermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='can_see_folder',
            field=models.BooleanField(default=False),
        ),
    ]
