# Generated by Django 5.2.3 on 2025-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='can_move_file',
            field=models.BooleanField(default=False),
        ),
    ]
