# Generated by Django 5.2.3 on 2025-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_folderpermission_can_see_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='can_see_members',
            field=models.BooleanField(default=False),
        ),
    ]
